// Auto-generated by skills/codebase-wiki/scripts/regenerate-sidebar.mjs
// Do not edit by hand; re-run the script after adding or renaming docs.

// @ts-nocheck

export const wikiSidebar = {
  "/architecture/": [
    {
      "text": "架构分析",
      "items": []
    }
  ],
  "/discussion/": [
    {
      "text": "技术讨论",
      "items": [
        {
          "text": "D-001 Orchestrator connect 去中心化设计讨论",
          "link": "/discussion/20260510-orchestrator-decentralized-connect"
        },
        {
          "text": "D-002 多 Page 到多 Pagelet 的 RPC 路由问题",
          "link": "/discussion/20260511-multi-page-routing-pagelet-proxy"
        },
        {
          "text": "D-003 Renderer 侧 directChannel 与 ipcChannel RPC 通道对比",
          "link": "/discussion/20260512-direct-channel-vs-ipc-channel-comparison"
        }
      ]
    }
  ],
  "/issue/": [
    {
      "text": "Issue 记录",
      "items": [
        {
          "text": "I-001 async-call-rpc-electron 心跳 ping 失败导致连接断开",
          "link": "/issue/20260510-async-call-rpc-electron-heartbeat-ping-bug"
        }
      ]
    }
  ],
  "/reference/": [
    {
      "text": "参考手册",
      "items": []
    }
  ],
  "/roadmap/": [
    {
      "text": "规划路线",
      "items": []
    }
  ]
};

export const wikiNav = [
  {
    "text": "首页",
    "link": "/INDEX"
  },
  {
    "text": "技术讨论",
    "link": "/discussion/20260510-orchestrator-decentralized-connect"
  },
  {
    "text": "Issue 记录",
    "link": "/issue/20260510-async-call-rpc-electron-heartbeat-ping-bug"
  }
];
